from enum import Enum
from datetime import datetime, timezone
from typing import List, Optional, Dict, Any, Tuple
from pydantic import BaseModel, Field


class SecurityVerdict(str, Enum):
    """Overall outcome of the security screening gate."""
    PASS = "PASS"        # Clean draft, no sensitive data or prompt injections detected
    REVIEW = "REVIEW"    # PII, internal margins, or confidential terms detected; requires human review
    BLOCK = "BLOCK"      # Critical security violation (prompt injection, active secret leak); blocked from sending


class SecurityCategory(str, Enum):
    """Categorization of security or compliance findings."""
    PII = "PII"
    PRIVATE_PRICING = "PRIVATE_PRICING"
    MARGINS = "MARGINS"
    CONFIDENTIAL_CONTRACT = "CONFIDENTIAL_CONTRACT"
    SECRETS = "SECRETS"
    PROMPT_INJECTION = "PROMPT_INJECTION"
    UNAUTHORIZED_INSTRUCTIONS = "UNAUTHORIZED_INSTRUCTIONS"


class SecuritySeverity(str, Enum):
    """Risk severity level of a detected finding."""
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"
    CRITICAL = "CRITICAL"


class SecurityFinding(BaseModel):
    """Individual sensitive finding or policy violation detected in draft text."""
    finding_id: str = Field(..., description="Unique finding ID (e.g. FIND-001)")
    category: SecurityCategory = Field(..., description="Classification category")
    severity: SecuritySeverity = Field(..., description="Severity level")
    description: str = Field(..., description="Human-readable explanation of why this was flagged")
    redacted_match: str = Field(..., description="Safely masked match snippet (never contains raw secrets)")
    character_span: Optional[Tuple[int, int]] = Field(None, description="Start and end char index in original text")
    suggested_replacement: str = Field(default="", description="Proposed safe sanitized replacement")


class SecurityScreeningReport(BaseModel):
    """
    Immutable audit report generated by the Security Screening Gate.
    Preserves original text without silent modifications and provides suggested sanitization.
    """
    screening_id: str = Field(..., description="Unique screening identifier (e.g. SEC-001)")
    case_id: str = Field(..., description="Associated case identifier")
    draft_id: str = Field(..., description="Associated draft identifier")
    timestamp_utc: datetime = Field(default_factory=lambda: datetime.now(timezone.utc), description="Screening timestamp")
    
    verdict: SecurityVerdict = Field(..., description="Overall verdict: PASS, REVIEW, or BLOCK")
    engine_used: str = Field(
        default="MODEL_ARMOR_LOCAL_FALLBACK",
        description="Explicit identifier of engine ('GOOGLE_MODEL_ARMOR_API' or 'MODEL_ARMOR_LOCAL_FALLBACK')"
    )
    
    findings_count: int = Field(default=0, description="Total number of detected issues")
    findings: List[SecurityFinding] = Field(default_factory=list, description="Itemized list of findings")
    
    original_text_preserved: str = Field(..., description="Original, unmodified draft body")
    suggested_sanitization: str = Field(..., description="Proposed sanitized draft with sensitive tokens replaced")
    action_taken: str = Field(..., description="Summary of action taken (e.g. 'Draft flagged for adjuster review')")
